package test.Phoenix.task.exceptions;

public class ApplicatonNotFoundException extends RuntimeException
{
    public ApplicatonNotFoundException(String message)
    {
        super(message);
    }
}
